### ISSUE TITLE
Read game-data from user documents

### ISSUE THREAD

**Issue by ascagnel** [tomkidd/Quake-iOS#1]
Would it be possible to read game data (eg `id0`, `id1`, `rogue`, and `hypnotic` folders) from the user’s documents (something like [this](https://developer.apple.com/documentation/bundleresources/information_property_list/uifilesharingenabled)).  You’d be able to work around the issue where users need to compile on their own to build a fully-working app.

**Comment by tomkidd** [comment]
I'm sure it's possible, and there's other things like being able to have the app spin up a web or ftp server long enough to send over the network to the device. 

This Quake 1 port in particular is one that, at some point, I'd like to redo using Quakespasm as a basis. The Cardboard VR port I co-opted is great but it has a handful of odd issues due to the way I modified it and I'd like all of these ports to be based off of popular source ports. 

Consequently this is something I'd probably do after that.
