### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by sebit144** [tomkidd/Quake-iOS#11]
How do you download it on mobile I don't see a download option maybe some help?

**Comment by tomkidd** [comment]
There's not a download since this is a source code project. 

I can't put Quake on the App Store since I don't own the rights to the game. I can't release a download outside of the App Store because the iPhone requires signed code. Releasing an unsigned version for the Jailbreak community is outside of the scope of this project. 

The way to run this on your phone is to use a Mac, Xcode, and build and push it to your own device.
