### ISSUE TITLE
Ok I have no clue on what to do.

### ISSUE THREAD

**Issue by Darthveder69420** [tomkidd/Quake-iOS#12]
What am I exactly supposed to do? I have a jailbroken iPad of that’s necessary but I have no idea as to what I am exactly supposed to. Is this like xash3d? I don’t see anything to download and I don’t understand as to what I am supposed to do. I can get an original copy of quake and its files but I have no idea as to what I am supposed to do after that.

**Comment by Darthveder69420** [comment]
Also can I get mods like slayers testaments running on this?

**Comment by tomkidd** [comment]
Hello, 

This repo contains the source code necessary to build an app version of Quake to run on your iOS and tvOS devices. It does not have a compiled or built version for downloading. You will need to use a Mac, a copy of Xcode, and an Apple Developer account to push it to your devices, which do not need to be jailbroken.

There are ways of building it into an unsigned bundle so that jailbroken devices or people managing their own code signing can use, but that's beyond the scope of this project. 

The thing I usually tell people is: if you don't have a Mac, make friends with someone who does :)

Also yes, with enough work any mods that don't require anything special (like a specific source port) should work, though outside of the expansion packs I've never tested any.

**Comment by Darthveder69420** [comment]
Oh well thats sad. Why wont you make a download and what is the the actual scope of the project? I don’t understand the scope of it

**Comment by tomkidd** [comment]
My goal was to see if I could get Quake 1 running on iOS and tvOS, so that's the extent of the project. 

Xcode is designed to produce signed bundles that can only run on specific devices and it's actually a fair amount of work to circumvent that, so I'd rather move on to more projects.

I'm aware that the source code nature of these ports will limit the appeal to those inclined to break out an iOS developer toolchain, but nevertheless I had fun doing it and thought I'd share it with others.
